# Generated by Django 6.0.6 on 2026-06-19 01:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('senhas', '0001_initial'),
        ('unidades', '0001_initial'),
        ('usuarios', '0002_alter_permissaosistema_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('matricula', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='FINALIZADO', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='usuarios.funcionario')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='categorias.categoriasenha')),
                ('senha', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='atendimento', to='senhas.senha')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='categorias.subcategoriasenha')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='unidades.unidadeatendimento')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'db_table': 'atendimentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
