# Generated by Django 6.0.6 on 2026-06-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
        ('usuarios', '0003_alter_permissaosistema_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_primaria', models.CharField(default='#FFE3A3', max_length=20)),
                ('cor_secundaria', models.CharField(default='#FFFFFF', max_length=20)),
                ('cor_fundo', models.CharField(default='#F5F5F5', max_length=20)),
                ('cor_texto', models.CharField(default='#000000', max_length=20)),
                ('som_chamada_url', models.CharField(blank=True, max_length=500, null=True)),
                ('som_chamada_ativo', models.BooleanField(default=True)),
                ('quantidade_historico_painel', models.PositiveIntegerField(default=5)),
                ('quantidade_proximas_painel', models.PositiveIntegerField(default=5)),
                ('ativo', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('unidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='unidades.unidadeatendimento')),
            ],
            options={
                'verbose_name': 'Configuração da unidade',
                'verbose_name_plural': 'Configurações das unidades',
                'db_table': 'configuracoes_unidade',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som_mudo', models.BooleanField(default=False)),
                ('cor_pagina', models.CharField(blank=True, max_length=20, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='usuarios.funcionario')),
            ],
            options={
                'verbose_name': 'Preferência do funcionário',
                'verbose_name_plural': 'Preferências dos funcionários',
                'db_table': 'preferencias_funcionario',
            },
        ),
    ]
