# Generated by Django 6.0.6 on 2026-06-19 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubspotTicketConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('REGISTRO_ATENDIMENTO', 'Registro de atendimento'), ('CHAMADO_INTERNO', 'Chamado interno')], max_length=30)),
                ('pipeline_id', models.CharField(max_length=120)),
                ('pipeline_nome', models.CharField(blank=True, max_length=180, null=True)),
                ('stage_id', models.CharField(max_length=120)),
                ('stage_nome', models.CharField(blank=True, max_length=180, null=True)),
                ('criar_automaticamente', models.BooleanField(default=False)),
                ('permitir_manual', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de ticket HubSpot',
                'verbose_name_plural': 'Configurações de tickets HubSpot',
                'db_table': 'hubspot_ticket_configs',
                'ordering': ['tipo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='IntegracaoHubspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('identificador', models.SlugField(max_length=80, unique=True)),
                ('base_url', models.URLField(default='https://api.hubapi.com')),
                ('token_acesso', models.TextField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integração HubSpot',
                'verbose_name_plural': 'Integrações HubSpot',
                'db_table': 'integracoes_hubspot',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HubspotCampoMapeado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriedade_hubspot', models.CharField(max_length=120)),
                ('nome_exibicao', models.CharField(blank=True, max_length=180, null=True)),
                ('origem', models.CharField(choices=[('CAMPO_SISTEMA', 'Campo do sistema'), ('VALOR_FIXO', 'Valor fixo'), ('CAMPO_FRONT', 'Campo informado no front')], default='CAMPO_SISTEMA', max_length=30)),
                ('campo_sistema', models.CharField(blank=True, choices=[('titulo', 'Título'), ('descricao', 'Descrição'), ('matricula', 'Matrícula'), ('cpf', 'CPF'), ('email', 'E-mail do aluno'), ('senha.codigo', 'Código da senha'), ('unidade.nome', 'Nome da unidade'), ('unidade.codigo', 'Código da unidade'), ('colaborador.nome', 'Nome do colaborador'), ('colaborador.email', 'E-mail do colaborador'), ('categoria.nome', 'Categoria'), ('subcategoria.nome', 'Subcategoria'), ('prioridade.nome', 'Prioridade'), ('finalizado_em', 'Data de finalização')], max_length=80, null=True)),
                ('chave_front', models.CharField(blank=True, max_length=120, null=True)),
                ('valor_fixo', models.TextField(blank=True, null=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('config_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_mapeados', to='integracoes.hubspotticketconfig')),
            ],
            options={
                'verbose_name': 'Campo mapeado HubSpot',
                'verbose_name_plural': 'Campos mapeados HubSpot',
                'db_table': 'hubspot_campos_mapeados',
                'ordering': ['config_ticket', 'ordem', 'propriedade_hubspot'],
            },
        ),
        migrations.CreateModel(
            name='HubspotTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REGISTRO_ATENDIMENTO', 'Registro de atendimento'), ('CHAMADO_INTERNO', 'Chamado interno')], max_length=30)),
                ('pipeline_id', models.CharField(blank=True, max_length=120, null=True)),
                ('stage_id', models.CharField(blank=True, max_length=120, null=True)),
                ('hubspot_ticket_id', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('payload_enviado', models.JSONField(blank=True, default=dict)),
                ('resposta_api', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubspot_logs', to='atendimentos.atendimento')),
                ('config_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_ticket', to='integracoes.hubspotticketconfig')),
                ('integracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_ticket', to='integracoes.integracaohubspot')),
            ],
            options={
                'verbose_name': 'Log de ticket HubSpot',
                'verbose_name_plural': 'Logs de tickets HubSpot',
                'db_table': 'hubspot_ticket_logs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='hubspotticketconfig',
            name='integracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_ticket', to='integracoes.integracaohubspot'),
        ),
    ]
