# Generated by Django 6.0.6 on 2026-06-18 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('unidades', '0001_initial'),
        ('usuarios', '0002_alter_permissaosistema_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadeSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(choices=[('NORMAL', 'Normal'), ('MEDIO', 'Médio'), ('PREFERENCIAL', 'Preferencial')], max_length=30, unique=True)),
                ('peso', models.PositiveIntegerField(default=1)),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('visivel_na_geracao', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prioridade de senha',
                'verbose_name_plural': 'Prioridades de senha',
                'db_table': 'prioridades_senha',
                'ordering': ['-peso', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('cpf', models.CharField(max_length=14)),
                ('humor', models.CharField(choices=[('FELIZ', 'Feliz'), ('NEUTRO', 'Neutro'), ('TRISTE', 'Triste')], default='NEUTRO', max_length=20)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CHAMADA', 'Chamada'), ('EM_ATENDIMENTO', 'Em atendimento'), ('PULADA', 'Pulada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('REDIRECIONADA', 'Redirecionada')], default='AGUARDANDO', max_length=30)),
                ('gerada_em', models.DateTimeField(auto_now_add=True)),
                ('chamada_em', models.DateTimeField(blank=True, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('pulada_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('redirecionada_em', models.DateTimeField(blank=True, null=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senhas', to='categorias.categoriasenha')),
                ('colaborador_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senhas_atuais', to='usuarios.funcionario')),
                ('colaborador_chamou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senhas_chamadas', to='usuarios.funcionario')),
                ('colaborador_finalizou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senhas_finalizadas', to='usuarios.funcionario')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senhas', to='senhas.prioridadesenha')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senhas', to='unidades.unidadeatendimento')),
            ],
            options={
                'verbose_name': 'Senha',
                'verbose_name_plural': 'Senhas',
                'db_table': 'senhas',
                'ordering': ['-prioridade__peso', 'gerada_em'],
            },
        ),
    ]
