# Generated by Django 6.0.6 on 2026-06-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0001_initial'),
        ('usuarios', '0002_alter_permissaosistema_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='colaborador_pulou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senhas_puladas', to='usuarios.funcionario'),
        ),
    ]
