# Generated by Django 6.0.6 on 2026-06-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0002_senha_colaborador_pulou'),
        ('usuarios', '0002_alter_permissaosistema_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='colaborador_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senhas_recebidas_redirecionamento', to='usuarios.funcionario'),
        ),
        migrations.AddField(
            model_name='senha',
            name='colaborador_redirecionou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senhas_redirecionadas', to='usuarios.funcionario'),
        ),
        migrations.AddField(
            model_name='senha',
            name='motivo_redirecionamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
