# Generated by Django 6.0.6 on 2026-06-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiches', '0001_initial'),
        ('senhas', '0003_senha_colaborador_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='guiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senhas_chamadas', to='guiches.guicheatendimento'),
        ),
    ]
