# Generated by Django 6.0.6 on 2026-06-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidade de atendimento',
                'verbose_name_plural': 'Unidades de atendimento',
                'db_table': 'unidades_atendimento',
                'ordering': ['nome'],
            },
        ),
    ]
