# Generated by Django 6.0.6 on 2026-06-18 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('COLABORADOR', 'Colaborador')], max_length=30, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de acesso',
                'verbose_name_plural': 'Perfis de acesso',
                'db_table': 'perfis_acesso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PermissaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('modulo', models.CharField(choices=[('UNIDADE', 'Unidade de atendimento'), ('COLABORADOR', 'Colaboradores'), ('CATEGORIA', 'Categorias de senha'), ('SUBCATEGORIA', 'Subcategorias de senha'), ('SENHA', 'Senhas'), ('FILA', 'Fila'), ('ATENDIMENTO', 'Atendimento'), ('RELATORIO', 'Relatórios'), ('PERMISSAO', 'Permissões'), ('INTEGRACAO', 'Integrações')], max_length=30)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permissão do sistema',
                'verbose_name_plural': 'Permissões do sistema',
                'db_table': 'permissoes_sistema',
                'ordering': ['modulo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='unidades.unidadeatendimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='usuarios.perfilacesso')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_do_perfil', to='usuarios.perfilacesso')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_com_permissao', to='usuarios.permissaosistema')),
            ],
            options={
                'verbose_name': 'Permissão do perfil',
                'verbose_name_plural': 'Permissões dos perfis',
                'db_table': 'perfil_permissoes',
                'unique_together': {('perfil', 'permissao')},
            },
        ),
        migrations.CreateModel(
            name='FuncionarioPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitido', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_individuais', to='usuarios.funcionario')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_com_permissao', to='usuarios.permissaosistema')),
            ],
            options={
                'verbose_name': 'Permissão individual',
                'verbose_name_plural': 'Permissões individuais',
                'db_table': 'funcionario_permissoes',
                'unique_together': {('funcionario', 'permissao')},
            },
        ),
    ]
