# Generated by Django 6.0.6 on 2026-06-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_permissaosistema_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaosistema',
            name='modulo',
            field=models.CharField(choices=[('UNIDADE', 'Unidade de atendimento'), ('COLABORADOR', 'Colaboradores'), ('CATEGORIA', 'Categorias de senha'), ('SUBCATEGORIA', 'Subcategorias de senha'), ('PRIORIDADE', 'Prioridades de senha'), ('SENHA', 'Senhas'), ('FILA', 'Fila'), ('ATENDIMENTO', 'Atendimento'), ('RELATORIO', 'Relatórios'), ('PERMISSAO', 'Permissões'), ('INTEGRACAO', 'Integrações'), ('CONFIGURACAO', 'Configurações'), ('GUICHE', 'Guichês')], max_length=30),
        ),
    ]
