# Generated by Django 6.0.6 on 2026-06-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
        ('usuarios', '0004_alter_permissaosistema_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuicheAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guiches_vinculados', to='usuarios.funcionario')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiches', to='unidades.unidadeatendimento')),
            ],
            options={
                'verbose_name': 'Guichê de atendimento',
                'verbose_name_plural': 'Guichês de atendimento',
                'db_table': 'guiches_atendimento',
                'ordering': ['unidade__nome', 'numero'],
                'unique_together': {('unidade', 'numero')},
            },
        ),
    ]
