# Generated by Django 6.0.6 on 2026-06-18 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de senha',
                'verbose_name_plural': 'Categorias de senha',
                'db_table': 'categorias_senha',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='categorias.categoriasenha')),
            ],
            options={
                'verbose_name': 'Subcategoria de senha',
                'verbose_name_plural': 'Subcategorias de senha',
                'db_table': 'subcategorias_senha',
                'ordering': ['categoria__nome', 'nome'],
                'unique_together': {('categoria', 'codigo'), ('categoria', 'nome')},
            },
        ),
    ]
